return {
	setup = function()
		require "nvim-treesitter.configs".setup({
			ensure_installed = {
				"bash",
				"comment",
				"css",
				"dockerfile",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gowork",
				"graphql",
				"html",
				"java",
				"javascript",
				"json",
				"json5",
				"jsonc",
				"kotlin",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"nix",
				"regex",
				"ruby",
				"scss",
				"sql",
				"terraform",
				"tsx",
				"typescript",
				"vim",
				"yaml",
			},
			highlight = {
				enable = true,
			},
			indent = {
				enable = true,
			},
		})

		vim.treesitter.language.register("html", "gohtml")
		vim.treesitter.language.register("terraform", "terraform-vars")
	end,
	filetypes = {
		"bash",
		"css",
		"dockerfile",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"gitrebase",
		"go",
		"gohtml",
		"gomod",
		"gowork",
		"graphql",
		"help",
		"html",
		"java",
		"javascript",
		"javascriptreact",
		"json",
		"kotlin",
		"lua",
		"make",
		"markdown",
		"nix",
		"ruby",
		"scss",
		"sh",
		"sql",
		"terraform",
		"terraform-vars",
		"tsx",
		"typescript",
		"typescriptreact",
		"vim",
		"yaml",
	}
}
