#!/usr/bin/env bash

possible_sessions=$({ (echo $CDPATH | awk -F: '{for(i=1;i<=NF;i++) print $i}' | grep -v '^\.$' | xargs -I _ find _ -type d -maxdepth 1) & (tmux list-sessions -F '#{?session_attached,,#{session_name}}' 2> /dev/null | sed '/^$/d'); })

selected=$(echo "$possible_sessions" | \
	FZF_DEFAULT_OPTS='--reverse --cycle' fzf --header "CTRL-S to create a session with that name; CTRL-X to kill a session;" --bind "ctrl-s:print-query+abort" --bind "ctrl-x:execute(tmux kill-session -t {})+reload(eval \"$possible_sessions\")")

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -d $selected ]]; then
	session_name=$(basename "$selected")
	directory=$selected
else
	session_name=$selected
fi

if ! tmux has-session -t="$session_name" 2> /dev/null; then
	if [[ -z "$directory" ]]; then
		tmux new-session -ds "$session_name"
	else
		tmux new-session -ds "$session_name" -c $selected
	fi
fi

if [[ $TMUX ]]; then
	tmux switch-client -t "$session_name"
else
	tmux attach -t "$session_name"
fi
