#!/usr/bin/env bash

possible_sessions="{ zoxide query -l & tmux list-sessions -F '#{?session_attached,,#{session_name}}' 2> /dev/null | sed '/^$/d'; }"

selected=$(eval "$possible_sessions" | \
	FZF_DEFAULT_OPTS='--reverse --cycle' fzf --query "$*" --select-1 --header "CTRL-S to create a session with that name; CTRL-X to kill a session;" --bind "ctrl-s:print-query+abort" --bind "ctrl-x:execute(tmux kill-session -t {})+reload(eval \"$possible_sessions\")") 

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ $TMUX ]]; then
	tmux switch-client -t $selected_name
else
	tmux attach -t $selected_name
fi
